project: 
  type: website
  output-dir: docs

website: 
  title: Welcome!
  navbar: 
    left: 
      - index.qmd
      - about.qmd
      - Redesign.qmd
      - FinalReport.qmd
      - aitpro.qmd
      

format: 
  html: 
    theme: united
  
