project: 
  type: website
  output-dir: docs

website: 
  title: Welcome!
  navbar: 
    left: 
      - href: index.qmd
        text: HOME
      - quali.qmd
      - about.qmd
      - Midproject.qmd
      - Redesign.qmd

format: 
  html: 
    theme: united
  