project: 
  type: website
  output-dir: docs

website: 
  title: Welcome!
  navbar: 
    left: 
      - href: index.qmd
        text: HOME
      - about.qmd
      - Redesign.qmd
      - Final_KW.qmd
      - Final_Report_Webpage.qmd

format: 
  html: 
    theme: united
  
