---
title: "WORK EXPERIENCE"
format: html
editor: visual
---

-   I completed an internship with Virtusa Consulting Services Pvt Ltd for 4 months.

-   I worked as an Associate Engineer at Virtusa Consulting Services Pvt Ltd for 1.6 years.

During this whole tenure at Virtusa, I was able to learn about AWS services and worked on a project and on a POC.

1.  POC

    Period: October 2023 – December 2023

    Role: Developer

    I worked on a POC, which requires extraction of data from the source database using SQL and converting existing Java code to python code and migrating that data into AWS cloud.

2.  BMO – Digital Core B2B – TIBCO BW to AWS

    Period: January 2023 – September 2023

    Role: Developer

    Migrating TIBCO on-premises API from on-premises servers to AWS Cloud Environment. This migration requires understanding the business logic and creating the request and response structure of the API from the TIBCO Designer and understanding the design given by the AWS architect.

Go back to [home](https://anushadusakanti15.github.io/).
